### PR TITLE
Added linux support.

### PR DESCRIPTION
**Pull request by sxe**
Hi, 
my first lua experiences.
Tested on my local system, please have a look.
Greetings

### CODE REVIEW

**Comment by sleighsoft** [comment]
Didn't the most recent version work for you?
And which flavor or linux do you use?
Thank you for your help :)

**Comment by sxe** [comment]
Hi,
no it did not. I had to add the missing parts in the code.
I am on archlinux 64bit.

**Comment by sleighsoft** [comment]
Done, tested it under Ubuntu as well.
Thank you for your help :+1:

**Comment by sxe** [comment]
Your welcome.
Btw, a good change would be, not to start a new vlc instance each time you choose a stream.
Would be better to play it in the current windows but i couldn't figure out how to do that, maybe you can.

Greetings.

**Comment by sleighsoft** [comment]
I think that's an option that is built into VLC itself.
It will prevent VLC from spawning multiple processes.
Tools > Preferences > Interfaces > Playlists and Instances > Allow only one Instance (checkbox)
This might work, I haven't tested it.
It could depend on how Livestreamer spawns the VLC stream.

Regards, Julian

**Comment by sxe** [comment]
Hi Julian, 
i already tried that option but it's not quit what i mean.
Your plugin creates a livestreamer process and that process itself spawns a new vlc instance what makes vlc crash, at least on my system. The best way would be to call the livestreamer script, get the created stream back and pass that on to the currently running vlc instance. At least i think that would be a good way, no idea if that is possible.

Greetings

**Comment by sleighsoft** [comment]
I might take a look into that, but it seems to be related more to livestreamer itself rather than the extension.

Regards, Julian

**Pull request merged**
